apiVersion: v1
kind: Service
metadata:
  name: user-preference-api
  namespace: legacy-services
spec:
  selector:
    app: user-preference-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
